repos:

  - repo: local
    hooks:
      - id: format
        name: Format Java source code
        entry: ./mvnw formatter:format -q
        types:
          - java
        language: system
        pass_filenames: false
        stages:
          - pre-commit

  - repo: local
    hooks:
      - id: verify
        name: Verify
        entry: ./mvnw verify
        types:
          - java
        language: system
        pass_filenames: false
        stages:
          - pre-push
